---

- name: Manage databases
  hosts: '{{ target }}'
  tasks:
   - name: Copy database to host system
     when: restore_backup is defined and restore_backup
     copy:
       src: "{{ db_file }}"
       dest: /home/ubuntu/{{ db_name }}/{{ db_name }}.db
       owner: "{{ default_user }}"
       group: "{{ gunicorn_group }}"
       mode: 0644

   - name: Drop database
     become_user: "{{ db_user }}"
     when: restore_backup is defined and restore_backup
     postgresql_db:
         db: "{{ db_name }}"
         encoding: 'UTF-8'
         lc_collate: 'en_US.UTF-8'
         lc_ctype: 'en_US.UTF-8'
         template: 'template0'
         state: absent

   - name: Create database
     become_user: "{{ db_user }}"
     when: restore_backup is defined and restore_backup
     postgresql_db:
         db: "{{ db_name }}"
         encoding: 'UTF-8'
         lc_collate: 'en_US.UTF-8'
         lc_ctype: 'en_US.UTF-8'
         template: 'template0'
         state: present

   - name: Restore file to database
     when: restore_backup is defined and restore_backup
     command: pg_restore -U {{ db_user }} -Fc -d {{ db_name }} /home/ubuntu/{{ db_name }}/{{ db_name }}.db

   - name: Current UTC time
     command: date +"%Y%m%d-%H%M" --universal
     register: current_time
     when: fetch_backup is defined and fetch_backup
     delegate_to: localhost

   - name: Create a database backup
     command: pg_dump -U {{ db_user }} -W {{ db_name }} -Fc -f {{ db_name }}-{{ current_time }}.db
     when: fetch_backup is defined and fetch_backup

   - name: Fetch database backup
     when: fetch_backup is defined and fetch_backup
     fetch:
       src: /home/ubuntu/{{ db_name }}-{{ current_time }}.db
       dest: "{{ db_name }}/"
       flat: yes