---

- name: Ensure bash, OpenSSL, and libssl are the latest versions
  apt: name={{ item }} update_cache={{ apt_update }} state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
  tags: packages

- name: Install base packages
  apt: name={{ item }} update_cache={{ apt_update }} force=yes state=installed
  with_items:
    - build-essential
    - git
    - nginx
    - supervisor
    - htop
    - python-dev
    - python-pip
    - python-virtualenv
  tags: packages

- name: Upgrade pip
  pip: name=pip state=latest
  tags: packages

- name: Create the application group
  group: name={{ gunicorn_group }} system=yes state=present
  tags: create_users

- name: Add the application user to the application group
  user: name={{ gunicorn_user }} group={{ gunicorn_group }} state=present
  tags: create_users